# Generated by Django 4.1.3 on 2022-12-21 15:05

from django.db import migrations


def init_data(apps, schema_editor):
    secondaries = apps.get_model('t9a', 'Secondaries')
    if not secondaries.objects.all():
        for s in ['Hold the Ground', 'Brakethrough', 'Spoils of War', 'King of the Hill', 'Capture the Flags',
                  'Secure Target']:
            sec = secondaries.objects.create(name=s)
            sec.save()

    army = apps.get_model('t9a', 'Army')
    if not army.objects.all():
        for a in [['BH', 'Beast Herds'],
                  ['DE', 'Dread Elves'],
                  ['DL', 'Daemon Legions'],
                  ['DH', 'Dwarven Holds'],
                  ['EoS', 'Empire of Sonnstahl'],
                  ['HbE', 'Highborn Elves'],
                  ['ID', 'Infernal Dwarves'],
                  ['KoE', 'Kingdom of Equitaine'],
                  ['OK', 'Ogre Kingdoms'],
                  ['OnG', 'Orcs and Goblins'],
                  ['SA', 'Saurian Ancients'],
                  ['SE', 'Sylvan Elves'],
                  ['UD', 'Undying Dynasties'],
                  ['VC', 'Vampire Covenant'],
                  ['VS', 'Vermin Swarm'],
                  ['WotDG', 'Warriors of the Dark Gods]']
                  ]:
            ar = army.objects.create(name=a[0], long_name=a[1])
            ar.save()

    maps = apps.get_model('t9a', 'Map')
    if not maps.objects.all():
        for m in ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8']:
            ma = maps.objects.create(name=m)
            ma.save()


class Migration(migrations.Migration):
    dependencies = [
        ('t9a', '0003_army_map_secondaries'),
    ]

    operations = [
        migrations.RunPython(init_data)
    ]
