# Generated by Django 4.1.3 on 2023-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t9a', '0007_alter_lists_options_alter_results_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'test'), (1, 'grand'), (2, 'local'), (3, 'friendly')], default=0),
        ),
    ]
