# Generated by Django 4.1.3 on 2023-01-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t9a', '0008_games_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'test'), (1, 'grand'), (2, 'local'), (3, 'friendly'), (4, 'league')], default=0),
        ),
    ]
