# Generated by Django 4.1.3 on 2023-01-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t9a', '0010_alter_games_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='uses_supplement',
            field=models.BooleanField(default=False),
        ),
    ]
