# Generated by Django 4.1.3 on 2023-01-06 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t9a', '0014_gaminggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaminggroup',
            name='members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
