# Generated by Django 4.1.3 on 2023-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t9a', '0018_listsunits_rename_data_save_results_save_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
