# Generated by Django 4.1.3 on 2023-01-16 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t9a', '0021_remove_results_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_percentage', models.IntegerField(choices=[(-2, '100%'), (-1, '50%'), (0, '0')])),
                ('special_points', models.BooleanField(default=False)),
                ('save_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t9a.listsunits')),
            ],
        ),
    ]
